name: Branches CI

on:
  # Trigger the workflow on push
  # but only for the non master branches
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        include:
          - os: ubuntu-20.04
            isMainHost: true #run jvm and js tests only on ubuntu
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            build/js
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.*') }} #hash based on *.gradle.kts and *.gradle.properties
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        env:
          isMainHost: ${{ matrix.isMainHost }}
        with:
          arguments: -PisMainHost="${isMainHost}" build --info --scan --no-daemon

  publish:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        include:
          - os: ubuntu-20.04
            isMainHost: true #needed for publication
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            build/js
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.*') }} #hash based on *.gradle.kts and *.gradle.properties
          restore-keys: ${{ runner.os }}-gradle
      - if: ${{ matrix.os == 'windows-latest' }}
        run: echo ("::set-env name=BRANCH_NAME::" + $env:GITHUB_REF.replace('refs/heads/', ''))
      - if: ${{ matrix.os != 'windows-latest' }}
        run: echo "##[set-env name=BRANCH_NAME;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: eskatos/gradle-command-action@v1
        env:
          isMainHost: ${{ matrix.isMainHost }}
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayKey: ${{ secrets.bintrayKey }}
          buildNumber: ${{ github.run_number }}
        with:
          arguments: -PisMainHost="${isMainHost}" -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" -PversionSuffix="-${BRANCH_NAME}-SNAPSHOT" -PbuildNumber="${buildNumber}" artifactoryPublish --stacktrace --no-daemon
