name: Branches CI

on:
  # Trigger the workflow on push
  # but only for the non master branches
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        include:
          - os: ubuntu-20.04
            isMainHost: true #run jvm and js tests only on ubuntu
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            build/js
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.*') }} #hash based on *.gradle.kts and *.gradle.properties
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --scan --no-daemon

  publish:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        include:
          - os: ubuntu-20.04
            isMainHost: true #needed for publication
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            build/js
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.*') }} #hash based on *.gradle.kts and *.gradle.properties
          restore-keys: ${{ runner.os }}-gradle
      - uses: eskatos/gradle-command-action@v1
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayKey: ${{ secrets.bintrayKey }}
          githubRef: ${{ github.ref }}
          buildNumber: ${{ github.run_number }}
        with:
          arguments: -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" -PversionSuffix="-${githubRef#refs/heads/}-SNAPSHOT" -PbuildNumber="${buildNumber}" artifactoryPublish --stacktrace --no-daemon
